### ISSUE TITLE
OSRM connection timeout causes instant optimisation stop

### ISSUE THREAD

**Issue by faustos** [TIXI24/sfitixi#190]
If one connection (checkConnectivity) to the osrm server times out, the whole optimisation process instantly stops. Expected behaviour: Retry for at least one more time before error escalation. 

![screen shot 2016-06-20 at 12 30 03](https://cloud.githubusercontent.com/assets/1834494/16191331/fccc8856-36e3-11e6-9e56-b8c976ef7bd1.png)

**Comment by Martin-Jonasse** [comment]
Dependancy(?); see issue https://github.com/TIXI24/sfitixi/issues/196

**Comment by Martin-Jonasse** [comment]
**Cause**:
- Sometimes, but not always, the OSRM Server hangs.
  - See https://github.com/Project-OSRM/osrm-backend/issues/58
  - See https://github.com/Project-OSRM/osrm-backend/issues/247
  - See https://github.com/Project-OSRM/osrm-backend/issues/1264
    ...
  - See https://github.com/Project-OSRM/osrm-backend/issues/3331
  - Comment: many closed while "not reproducible"
- Then as soon as the app needs a route it will call checkConnectivity()
- Then the app throws an exception and you get the error message displayed above.

**Critique**:
- The TIXI24 application is totally dependant on OSRM and does not attempt the workaround.

**Workaround**:
- The timeout happens in the simple database defined for tixi-linth (**reproducable**).
- After approx. 20 production plan days the application hangs and throws an exception.
- Testing the interface using curl (or browser) displays a timeout.
- Retrys have no effect: the error is persistant (memory leaks?).
- After restarting the server the service is OK again.

**Comment by Martin-Jonasse** [comment]
Fixed, details see iTIXI_use_case_routing_service.docx.

**Comment by daniel-j-h** [comment]
:wave: Just a quick follow up - was the issue on the osrm side? How did you fix it?

Also did you try to use [node-osrm](https://github.com/Project-OSRM/node-osrm) and a Node HTTP server?

**Comment by Martin-Jonasse** [comment]
The issue is probably an error in the OSM map, the osrm backend server (v5.1) just failed (returned nothing at all).

Fix: 
1. build a baseline matrix for the region of interest (city of Basel CH).
2. get route from osrm backend and from the baseline matrix
3. check both:
3.1 if osrm route is missing, use baseline (and also restart osrm backend)
3.2 if osrm route is 200% of baseline, use baseline 

The latter is also an issue if the map contains roads, junctions with bad connections.
One route returned 90km instead of 2km. This needs to be detected too (3.2).

No, I did not try to use node-osrm, the osrm-backend is tightly integrated into the TIXI24 app.
Using another server is not a solution due to the fact that the map (mappers) are the problem.

Kind regards

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 03.03.2017 um 15:50 schrieb Daniel J. H. <notifications@github.com>:
